import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
    return (
        <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
            <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
            <p style={{ fontSize: "18px", marginBottom: "30px" }}>
                This project was generated By{" "}
                <a href="#" style={{ color: "#87CEFA", textDecoration: "none" }}>
                
                </a>
            </p>
            <p>Quickly use below links to navigate through all pages.</p>
            <ul style={{ listStyle: "none", padding: "0" }}>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/registerpagecoloured" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        RegisterPageColoured
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/loginpagecoloured" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        LoginPageColoured
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/homepagecoloured" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        HomePageColoured
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/projectscolored" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        ProjectsColored
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/moreinfopageforaprojectprev" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        More InfoPageforaProjectPrev
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/gisintegrationwindowcolored" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        GISIntegrationWindowColored
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/aboutuscolored" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        AboutUsColored
                    </Link>
                </li>
            </ul>
        </div>
    );
};

export default Home;
